CREATE TABLE public.users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email character varying(255) NOT NULL,
    login character varying(255) NOT NULL,
    name character varying(255),
    birthday date,
    password character varying(255) NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    CONSTRAINT users_login_unique UNIQUE (login),
    CONSTRAINT users_email_unique UNIQUE (email)
);
