CREATE TABLE public.genre
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT genre_pk_2 UNIQUE (name)
);