CREATE TABLE IF NOT EXISTS public.mpa_rating
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT mpa_rating_pk_2 UNIQUE (name)
)