CREATE TABLE public.films
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    description character varying COLLATE pg_catalog."default",
    release_date date,
    duration integer,
    rating numeric(3,1),
    mpa_id integer,
    CONSTRAINT fkf363q5g91pxhibc2l91mlru0e FOREIGN KEY (mpa_id)
        REFERENCES public.mpa_rating (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE INDEX idx_films_mpa_id ON public.films (mpa_id);

CREATE INDEX idx_films_name ON public.films (name);

CREATE INDEX idx_films_rating ON public.films (rating);

CREATE INDEX idx_films_release_date ON public.films (release_date);