CREATE TABLE public.review
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text character varying,
    rating numeric(3,1),
    film_id bigint,
    user_id bigint,
    CONSTRAINT fk_film FOREIGN KEY (film_id)
        REFERENCES public.films (id)
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT fk_user FOREIGN KEY (user_id)
        REFERENCES public.users (id)
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);