CREATE TABLE public.friendship
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    friend_id bigint NOT NULL,
    status varchar,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone,
    CONSTRAINT unique_friendship UNIQUE (user_id, friend_id),
    CONSTRAINT friendship_friend_id_fkey FOREIGN KEY (friend_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT friendship_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT not_same_user CHECK (user_id <> friend_id)
);

CREATE INDEX idx_friendship_friend_user ON public.friendship (friend_id, user_id);

CREATE INDEX IF NOT EXISTS idx_friendship_user_friend ON public.friendship (user_id, friend_id);